import React, { useState, useEffect } from 'react';
import './App.css';

import Sidebar from './Components/Sidebar/Sidebar.jsx';
import Header from './Components/Header/Header.jsx';
import JobTable from './Components/JobTable/JobTable.jsx';
import FilterModal from './Components/FilterModal/FilterModal.jsx';
import NotesModal from './Components/NotesModal/NotesModal.jsx';
import AddJobModal from './Components/AddJobModal/AddJobModal.jsx';

// Backend API base URL - matches your existing backend configuration
const API_BASE_URL = 'http://localhost:3001/api';  // Development URL matching your backend PORT=3001

const App = () => {
  // TODO: Create state for jobs array using useState
  // TODO: Initialize with sample data or empty array
  // TODO: Sample data structure should be array of objects with:
  // TODO: - id (unique number)
  // TODO: - company (string - company name)
  // TODO: - jobTitle (string - position title)
  // TODO: - status (string - 'Applied', 'Interviewing', 'Offer', 'Rejected')
  // TODO: - applicationDate (string - MM/DD/YYYY format)
  // TODO: - notes (string - application notes)

  // State for jobs array - now populated from your backend API instead of sample data
  const [jobs, setJobs] = useState([]);
  
  // Loading state to show when API calls are in progress
  const [loading, setLoading] = useState(true);
  
  // Error state to handle and display API errors
  const [error, setError] = useState(null);

  // TODO: Create state for search functionality
  // TODO: - searchTerm (string for filtering by company name)
  const [searchTerm, setSearchTerm] = useState('');

  // TODO: Create state for filter functionality  
  // TODO: - activeFilters (array of status strings to filter by)
  const [activeFilters, setActiveFilters] = useState(['Applied', 'Interviewing', 'Offer', 'Rejected']);

  // TODO: Create state for modal visibility
  // TODO: - showNotesModal (boolean)
  const [showNotesModal, setShowNotesModal] = useState(false);
    // TODO: - selectedJob (object - currently selected job for editing)
  const [selectedJob, setSelectedJob] = useState(null);

  // TODO: - showAddJobModal (boolean
  const [showAddJobModal, setShowAddJobModal] = useState(false);
  // TODO: - showFilterModal (boolean)
  const [showFilterModal, setShowFilterModal] = useState(false);

  // GET - Fetch all jobs from your backend on component mount
  useEffect(() => {
    const fetchJobs = async () => {
      try {
        setLoading(true);
        setError(null);
        
        // Call your backend's GET /api/jobs endpoint
        const response = await fetch(`${API_BASE_URL}/jobs`);
        
        // Check if response is successful
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        // Parse response - your backend returns {success: true, data: jobs}
        const result = await response.json();
        
        // Extract jobs array from your backend's response structure
        if (result.success && result.data) {
          setJobs(result.data);
        } else {
          throw new Error('Invalid response format from server');
        }
      } catch (error) {
        console.error('Error fetching jobs:', error);
        setError('Failed to load jobs. Please try again.');
        
        // Fallback to sample data if backend is unavailable
        setJobs([
          {
            id: 1,
            company: 'Apple',
            jobTitle: 'Software Developer',
            status: 'Rejected',
            applicationDate: '07/03/2025',
            notes: 'Improve on OA coding skills and system design preparation'
          },
          {
            id: 2,
            company: 'Amazon',
            jobTitle: 'Software Developer',
            status: 'Applied',
            applicationDate: '07/05/2025',
            notes: 'Practice More Leetcode problems, especially dynamic programming'
          }
        ]);
      } finally {
        setLoading(false);
      }
    };

    fetchJobs();
    // dependency empty array so runs once on mount
  }, []);

  // CREATE - Add new job using your backend's POST /api/jobs endpoint
  const createJob = async (newJob) => {
    try {
      setLoading(true);
      setError(null);
      
      // Call your backend's POST endpoint with required fields
      const response = await fetch(`${API_BASE_URL}/jobs`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          company: newJob.company,
          jobTitle: newJob.jobTitle,
          status: newJob.status,
          notes: newJob.notes
          // applicationDate and id will be generated by your backend
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
      }

      // Parse response - your backend returns {success: true, message: string, data: job}
      const result = await response.json();
      
      if (result.success && result.data) {
        // Update local state with the new job from backend
        setJobs(prevJobs => [...prevJobs, result.data]);
        return result.data;
      } else {
        throw new Error('Invalid response format from server');
      }
    } catch (error) {
      console.error('Error creating job:', error);
      setError(`Failed to create job: ${error.message}`);
      throw error;
    } finally {
      setLoading(false);
    }
  };

  // UPDATE - Update existing job using your backend's PATCH /api/jobs/:id endpoint
  const updateJob = async (id, updatedFields) => {
    try {
      setLoading(true);
      setError(null);
      
      // Call your backend's PATCH endpoint with only the fields to update
      const response = await fetch(`${API_BASE_URL}/jobs/${id}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(updatedFields)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
      }

      // Parse response - your backend returns {success: true, message: string, data: job}
      const result = await response.json();
      
      if (result.success && result.data) {
        // Update local state with the updated job
        setJobs(prevJobs =>
          prevJobs.map(job =>
            job.id === id ? result.data : job
          )
        );
        return result.data;
      } else {
        throw new Error('Invalid response format from server');
      }
    } catch (error) {
      console.error('Error updating job:', error);
      setError(`Failed to update job: ${error.message}`);
      throw error;
    } finally {
      setLoading(false);
    }
  };

  // DELETE - Remove job using your backend's DELETE /api/jobs/:id endpoint
  const deleteJob = async (id) => {
    try {
      setLoading(true);
      setError(null);
      
      // Call your backend's DELETE endpoint
      const response = await fetch(`${API_BASE_URL}/jobs/${id}`, {
        method: 'DELETE'
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
      }

      // Parse response - your backend returns {success: true, message: string}
      const result = await response.json();
      
      if (result.success) {
        // Update local state by removing the deleted job
        setJobs(prevJobs => prevJobs.filter(job => job.id !== id));
        return true;
      } else {
        throw new Error('Invalid response format from server');
      }
    } catch (error) {
      console.error('Error deleting job:', error);
      setError(`Failed to delete job: ${error.message}`);
      throw error;
    } finally {
      setLoading(false);
    }
  };

  // TODO: Create handler for opening notes modal
  // TODO: - Accept job object as parameter
  // TODO: - Set selectedJob to the clicked job
  // TODO: - Set showNotesModal to true
  const handleNotesClick = (job) => {
    setSelectedJob(job);
    setShowNotesModal(true);
  };

  // TODO: Create handler for updating job status
  // TODO: - Accept jobId and newStatus as parameters
  // TODO: - Update the jobs array by finding job with matching id
  // TODO: - Change the status property to newStatus
  // Updates the status of a specific job - now calls backend API instead of direct state manipulation
  // jobId: the id of the job to update
  // newStatus: the new status value to set
  const handleStatusChange = async (jobId, newStatus) => {
    try {
      // Update only the status field using PATCH API call to your backend
      await updateJob(jobId, { status: newStatus });
    } catch (error) {
      console.error('Error updating job status:', error);
      // Error handling is already done in updateJob function
    }
  };

  // TODO: Create handler for adding new job
  // TODO: - Accept newJob object as parameter
  // TODO: - Generate new unique id
  // TODO: - Add current date as applicationDate
  // TODO: - Add newJob to jobs array
  // TODO: - Close the add job modal

  // Handler for adding new job - now creates job in backend instead of local manipulation
  // Accept newJob object as parameter
  // Backend generates unique id and adds current date as applicationDate
  // Add newJob to jobs array via API call and close the add job modal
  const handleAddJobSubmit = async (newJob) => {
    try {
      // Create job in backend (backend will generate unique ID and applicationDate)
      await createJob(newJob);
      
      // Close the modal after successful creation
      setShowAddJobModal(false);
    } catch (error) {
      console.error('Error adding job:', error);
      // Error state is already handled in createJob function
    }
  };

  // TODO: Create handler for updating filters
  // TODO: - Accept filters array as parameter
  // TODO: - Update activeFilters state
  const handleFilterChange = (filters) => {
    setActiveFilters(filters);
  };

  // TODO: Create handler for filter click (opens filter modal)
  // TODO: - Set showFilterModal to true
  // TODO: - This is called when filter icon in sidebar is clicked
  const handleClickFilterClick = () => {
    setShowFilterModal(true);
  };

  // TODO: Create handler for opening add job modal
  // TODO: - Set showAddJobModal to true
  // TODO: - This is called when "Add Job" button is clicked
  const handleAddJobClick = () => {
    setShowAddJobModal(true);
  };

  // TODO: Create handler for deleting jobs
  // TODO: - Accept jobId as parameter
  // TODO: - Remove job from jobs array
  // TODO: - Show confirmation before deletion
  // Handler for deleting jobs - calls backend API to delete job and updates local state
  // jobId: the id of the job to delete
  // Shows confirmation dialog before deletion for better UX
  const handleDeleteJob = async (jobId) => {
    // Show confirmation dialog before deleting
    const confirmDelete = window.confirm('Are you sure you want to delete this job application? This action cannot be undone.');
    
    if (!confirmDelete) {
      return; // User cancelled deletion
    }

    try {
      // Call backend DELETE endpoint to remove job
      await deleteJob(jobId);
    } catch (error) {
      console.error('Error deleting job:', error);
      // Error handling is already done in deleteJob function
    }
  };

  // TODO: Create handler for closing modals
  // TODO: - Set all modal states to false (showNotesModal, showAddJobModal, showFilterModal)
  // TODO: - Reset selectedJob to null
  // TODO: - This can be reused for all modal close actions

  // TODO: Create handler for notes submission
  // TODO: - Accept jobId and newNotes as parameters
  // TODO: - Update the jobs array by finding job with matching id
  // TODO: - Update the notes property with newNotes
  // TODO: - Close the notes modal
  // Handler for notes submission - now updates backend instead of direct state manipulation
  // Accept jobId and newNotes as parameters
  // Update the job's notes via API call and close the notes modal
  const handleNotesSubmit = async (jobId, newNotes) => {
    try {
      // Update only the notes field using PATCH API call to your backend
      await updateJob(jobId, { notes: newNotes });
      
      // Close the notes modal after successful update
      setShowNotesModal(false);
      setSelectedJob(null);
    } catch (error) {
      console.error('Error updating job notes:', error);
      // Error handling is already done in updateJob function
    }
  };

  // TODO: Create filtering logic for jobs display
  // TODO: - Filter jobs by searchTerm (company name includes search)
  // TODO: - Filter jobs by activeFilters (status matches selected filters)
  const filteredJobs = jobs.filter(job => {
    // Filter by search term
    const matchesSearch = job.company.toLowerCase().includes(searchTerm.toLowerCase());
   
    // Filter by active filters
    const matchesFilter = activeFilters.includes(job.status);
   
    // Return true if both conditions are met
    return matchesSearch && matchesFilter;
  });
  // TODO: - Return filtered array to pass to JobTable

  // Show loading spinner while fetching data from backend
  if (loading && jobs.length === 0) {
    return (
      <div className="app" style={{ justifyContent: 'center', alignItems: 'center' }}>
        <div>Loading jobs...</div>
      </div>
    );
  }

  return (
    <div className="app">
      <Sidebar
        // TODO: Pass filter click handler as prop
        onFilterClick={handleClickFilterClick}
      />
     
      <div className="main-content">
        <Header
          // TODO: Pass searchTerm state as prop (note the difference in prop name and state name)
          searchTerm={searchTerm}
          // TODO: Pass search change handler as prop (note change depending on paramter for setSearchTerm depding on value change in child component)
          onSearchChange={(term) => setSearchTerm(term)}
          // TODO: Pass add job click handler as prop
          onAddJobClick={handleAddJobClick}
        />

        {/* Display error message if there's an API error */}
        {error && (
          <div style={{ 
            background: '#ff4757', 
            color: 'white', 
            padding: '10px', 
            margin: '10px',
            borderRadius: '5px' 
          }}>
            {error}
            <button 
              onClick={() => setError(null)}
              style={{ 
                marginLeft: '10px', 
                background: 'transparent', 
                border: '1px solid white', 
                color: 'white',
                borderRadius: '3px',
                cursor: 'pointer'
              }}
            >
              Dismiss
            </button>
          </div>
        )}
       
        <JobTable
          // TODO: Replace with your filtered jobs array
          jobs={filteredJobs}
          // TODO: Pass status change handler as prop
          onStatusChange={handleStatusChange}
          // TODO: Pass notes click handler as prop
          onNotesClick={handleNotesClick}
          // TODO: Pass delete job handler as prop
          onDeleteJob={handleDeleteJob}
        />
      </div>

      {/* TODO: Conditionally render NotesModal when showNotesModal is true */}
      {/* TODO: Pass selectedJob, close handler, and submit handler as props */}
      {showNotesModal && selectedJob && (
        <NotesModal
          job={selectedJob}
          onClose={() => {
            setShowNotesModal(false);
            setSelectedJob(null);
          }}
          onSubmit={handleNotesSubmit}
        />
      )}

      {/* TODO: Conditionally render AddJobModal when showAddJobModal is true */}
      {/* TODO: Pass close handler and submit handler as props */}
      {showAddJobModal && (
        <AddJobModal
          onClose={() => setShowAddJobModal(false)}
          onSubmit={handleAddJobSubmit}
        />
      )}

      {/* TODO: Conditionally render FilterModal when showFilterModal is true */}
      {/* TODO: Pass activeFilters, close handler, and filters change handler as props */}
      {showFilterModal && (
        <FilterModal
          onClose={() => setShowFilterModal(false)}
          activeFilters={activeFilters}
          onFiltersChange={handleFilterChange}
        />
      )}
    </div>
  );
};

export default App;